### PR TITLE
[ADD] sale_subscription_suspend

### PR DESCRIPTION
**Pull request by brian10048**
@max3903 please review for #118

### CODE REVIEW

**Comment by max3903** [comment]
Ping @kvedder-amplex, @barnarj

**Comment by kvedder-amplex** [comment]
I didn't load it into a container and test, but gave the code a once over and it looks good.

**Comment by kvedder-amplex** [comment]
@brian10048 @max3903 added this to a branch in my CI/CD pipeline and built an instance. It works well, I would just move the Suspended Column in the kanban view over to the right. Also move the suspend button over.

image

image

After, should be good to merge! Thanks Brian.

**Comment by brian10048** [comment]
@kvedder-amplex @max3903 

Thank you for the feedback!  I originally put the Suspended column after Progress as you have requested.  The issue I had was when re-activating the subscription.  For simplicity I just called the existing set_open method to re-activate and it was putting the subscription into Upsell because how set_open method works.  My solution was to lower the sequence of the stage before Progress.  

If you want the Suspend stage after Progress, I will go ahead and modify the re-activate method to put the subscription into the Progress state accordingly.

Moving the button is a quick fix.

I should have some time this weekend to make the changes

**Comment by brian10048** [comment]
When I move the 'Suspend' column to the right of 'In Progress' there is an issue caused by the subscription `set_close` method.  The `set_close` method searches the next stage in sequence that has a False value for `in_progress`  As a result, when attempting to close a subscription either manually with the close button or automatically via a failed payment for instance, the subscription ends up in the 'Suspend' state rather than going to 'Close' state because 'Suspend' is before 'Close' in sequence.  

I could completely overwrite the `set_close` method, but I'm not sure that is a good idea.  

@max3903 any recommendations?

**Comment by kvedder-amplex** [comment]
If it's crazy to do, then it likely isn't worth the time.

**Comment by max3903** [comment]
Would pushing the "Suspended" stage to the end, after the "Closed" one, be a working option?

**Comment by brian10048** [comment]
@max3903 - Yes, it works as intended if the "Suspended" stage is after the "Close" stage

@kvedder-amplex let me know which way you prefer:

Option A:  "Suspended" before "In Progress" as initially done
Option B:  "Suspended" after "Close" stage

If Option B, would you like the button for Suspend to be after or before Close?

**Comment by kvedder-amplex** [comment]
Let's put it after the Close Stage. Thanks for working this out.

**Comment by brian10048** [comment]
@max3903 @kvedder-amplex 

👍 Changes made

**Comment by max3903** [comment]
@brian10048 Can you add this module to the exclude list in .travis.yml so we can merge this? Thanks!

**Comment by brian10048** [comment]
@max3903 Looks like you got the exlcusion for travis.  For future reference, is this something that is needed when depending on enterprise modules?

**Comment by max3903** [comment]
@brian10048 Yes.

**Pull request merged**
