### PR TITLE
[16.0][ADD] mrp_consu_aml

### PR DESCRIPTION
**Pull request by Murtaza-OSI**

### CODE REVIEW

**Comment by Urvisha-OSI** [comment]
@agyamuta Pre-commits are failing because of the osi_auth_oauth module and this module is not available in this branch, so we can not fix that module issue here, the test fails because of the Authentication failed for 'https://github.com/ursais/osi-addons/', i think @dreispt should look at this

**Comment by dreispt** [comment]
@Urvisha-OSI Yes - Missing ./README.rst file. Please add it in a separate commit, to fix the pre-commit checks.

**Comment by Urvisha-OSI** [comment]
> @Urvisha-OSI Yes - Missing ./README.rst file. Please add it in a separate commit, to fix the pre-commit checks.

@dreispt missing README.rst file in osi_auth_oauth module that module is not available in this branch, should I do a new separate PR for it?

**Comment by Urvisha-OSI** [comment]
refer https://github.com/ursais/osi-addons/pull/526 PR for resolve osi_auth_oauth module

**Pull request closed without merging**
