### PR TITLE
Rename Avatax module to osi_avatax_connector

### PR DESCRIPTION
**Pull request by dreispt**
This avoids name conflicts with the App Store pre-existing modules.

### CODE REVIEW

**Comment by dreispt** [comment]
Update: I contacted Fabrice to check viability of getting ownership of the original module identifier name. This PR should be freezed until we get a final answer.

**Comment by max3903** [comment]
@dreispt Can you fix the Travis errors?

**Comment by dreispt** [comment]
@max3903 Lint errors only. I can, but I have no budget left, so would have to be "homework". If should go in a separate PR.

**Comment by dreispt** [comment]
I don't have any progress from my contacts with OdooApps and Sodexis, so I'm moving forward with the name change.

**Pull request merged**
