### PR TITLE
[14.0][FIX]fieldservice_helpdesk_stock

### PR DESCRIPTION
**Pull request by Vimal-OSI**
Error: When creating an Stock Request Order and adding items, no routes show. 
Ticker ref: https://pm.opensourceintegrators.com/web#id=11001&action=324&model=helpdesk.ticket&view_type=form&menu_id=218

### CODE REVIEW

**Comment by patrickrwilson** [comment]
@Vimal-OSI Please fix pre-commit

**Comment by patrickrwilson** [comment]
@Vimal-OSI please fix pre-commit

**Review by osi-scampbell — APPROVED** [review]

**Comment by Vimal-OSI** [comment]
> @Vimal-OSI please fix pre-commit

Done the changes, PR is fully green now

**Review by patrickrwilson — APPROVED** [review]
LGTM

**Pull request merged**
