### PR TITLE
[MIG][12.0] agreement_sale_subscription

### PR DESCRIPTION
**Pull request by murtuzasaleh**
WIP

### CODE REVIEW

**Review by osi-scampbell — COMMENTED** [review]
For this oca_depends.txt, we need sale_subscription because it is an enterprise module, and we also need to make sure we include agreement_legal_sale as well.

**Comment by murtuzasaleh** [comment]
@max3903 Any Idea for failing Travis?
It gives below error.
File "/home/travis/maintainer-quality-tools/travis/test_pylint", line 59, in <module>
    result = run_pylint.pylint_run(is_pull_request, version, git_work_dir)
  File "/home/travis/maintainer-quality-tools/travis/run_pylint.py", line 168, in pylint_run
    real_errors = main(cmd, standalone_mode=False)
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/travis/maintainer-quality-tools/travis/run_pylint.py", line 308, in main
    extra_params=extra_params)
  File "/home/travis/maintainer-quality-tools/travis/run_pylint.py", line 278, in run_pylint
    pylint_res = pylint.lint.Run(cmd, exit=False)
TypeError: __init__() got an unexpected keyword argument 'exit'

**Comment by murtuzasaleh** [comment]
> For this oca_depends.txt, we need sale_subscription because it is an enterprise module, and we also need to make sure we include agreement_legal_sale as well.

@max3903 So can I add enterprise 12.0 branch in oca_dependencies.txt file?

**Comment by max3903** [comment]
@murtuzasaleh No, but please rebase and add this module to the exclude list.

**Comment by murtuzasaleh** [comment]
@max3903 @osi-scampbell Can you please review this PR.

**Review by osi-scampbell — APPROVED** [review]

**Review by max3903 — APPROVED** [review]

**Pull request merged**
