### PR TITLE
[14.0] [ADD] osi_helpdesk_sale: Added new module to create sale orders from helpdesk ticket.

### PR DESCRIPTION
**Pull request by Chandresh-OSI**
Wiki: https://wiki.ursasys.net/en/home/Projects/Ska_Fabricating/Designs/Helpdesk-Sales

### CODE REVIEW

**Review by patrickrwilson — CHANGES_REQUESTED** [review]
When clicking the 'create ticket' or 'create sale order' buttons it's opening the new record in a popup window due to target=new. This causes a few challenges as it won't show the commonly used chatter on the tickets, and for the sale order adding a configurable product causes the popup to disappear. It would be better to open the full form instead of popups.

**Comment by Chandresh-OSI** [comment]
@patrickrwilson I have removed target=new from action. It is fixed now.

**Review by patrickrwilson — APPROVED** [review]
Tested and works great. LGTM

**Comment by patrickrwilson** [comment]
@omahadik this is ready for your review.

**Review by omahadik — APPROVED** [review]

**Comment by omahadik** [comment]
@patrickrwilson Looks good. Added my approval. 
When can we get this merged to the 14.0 branch?

**Pull request merged**
