### PR TITLE
[FIX]Added carry over for agreement and service profile

### PR DESCRIPTION
**Pull request by osimallen**

### CODE REVIEW

**Comment by max3903** [comment]
@osimallen This should go in a separate module `helpdesk_fieldservice_agreement` that depends on `helpdesk_fieldservice` and `agreement_helpdesk` with `'auto_install': True`.

**Review by max3903 — CHANGES_REQUESTED** [review]
Requested a separate module to allow installing helpdesk_fieldservice without agreement

**Comment by osimallen** [comment]
@max3903 I've updated the PR to add the carry over of the agreement values in a new module instead of modifying helpdesk_fieldservice to make it depend on agreement. Please re-review. Thanks.

**Review by max3903 — APPROVED** [review]

**Comment by max3903** [comment]
@osimallen Can you fix the flake8 error?

**Comment by osimallen** [comment]
@max3903 The only flake8 errors I see are in helpdesk_fieldservice_stock files which aren't a part of my commits. I can fix them in this branch if you want though if it'll save you time.

**Comment by max3903** [comment]
@osimallen Yes please! Thanks.

**Comment by osimallen** [comment]
@max3903 Lint errors should be fixed

**Comment by max3903** [comment]
@osimallen Can you add this new module in the list of excluded ones in .travis.yml?

**Comment by osimallen** [comment]
> @osimallen Can you add this new module in the list of excluded ones in .travis.yml?

Done

**Review by max3903 — APPROVED** [review]

**Pull request merged**
