### PR TITLE
[WIP][ADD] osi_bank_reconciled_report

### PR DESCRIPTION
**Pull request by osi-scampbell**
This module creates a new report underneath the Reconciliation Report that shows unreconciled bank statement lines as well as reconcilied bank statement lines.

WIP because of pylint errors. Will be fixed very soon.

### CODE REVIEW

**Review by patrickrwilson — CHANGES_REQUESTED** [review]
I think the order needs to be updated, they would like the reconciled items to show under the reconciled items. Probably same with all other items, the pattern should be, first show the reconciled group then the same related reconciled group after. Let me know if you have questions.

**Review by patrickrwilson — APPROVED** [review]
Looks good. Missing your OSI logo for the app but approving since that is optional anyway.

**Review by smangukiya — APPROVED** [review]
ready for functional review

**Comment by dreispt** [comment]
\o/

**Pull request merged**
