### PR TITLE
[IMP] osi_fifo_serialized_fix

### PR DESCRIPTION
**Pull request by Freni-OSI**
Task: https://pm.opensourceintegrators.com/web?debug=1#id=16314&model=project.task&view_type=form&menu_id=176
Improved https://github.com/ursais/osi-addons/pull/369

### CODE REVIEW

**Comment by Hardik-OSI** [comment]
Hello @max3903 
In This Branch Pre Commit Failed due to account_bank_statement_extend module. 
for account_bank_statement_extend module pre-commit fixed in https://github.com/ursais/osi-addons/tree/14.0-fix-analytic_segments_defaults This Branch so once you merge this branch pre-commit Fixed.
Thanks.

**Review by smangukiya — APPROVED** [review]
LGTM

**Comment by smangukiya** [comment]
@Hardik-OSI : Can you please fix this part:

Got this error when trying to validate a pick - Error:
Odoo Server Error

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 684, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 360, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 348, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 913, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 532, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 1393, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 1381, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 396, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 383, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/stock/wizard/stock_backorder_confirmation.py", line 69, in process_cancel_backorder
    return self.env['stock.picking']\
  File "/odoo/addons/osi_partner_credit_limit/models/stock_picking.py", line 57, in button_validate
    return super(StockPicking, self).button_validate()
  File "/odoo/addons/osi_manual_qty_reserve/models/stock_picking.py", line 11, in button_validate
    res = super(StockPicking, self).button_validate()
  File "/usr/lib/python3/dist-packages/odoo/addons/stock/models/stock_picking.py", line 954, in button_validate
    pickings_not_to_backorder.with_context(cancel_backorder=True)._action_done()
  File "/odoo/addons/kudu_stock/models/stock_picking.py", line 10, in _action_done
    res = super()._action_done()
  File "/usr/lib/python3/dist-packages/odoo/addons/sale_stock/models/stock.py", line 91, in _action_done
    res = super()._action_done()
  File "/usr/lib/python3/dist-packages/odoo/addons/stock/models/stock_picking.py", line 775, in _action_done
    todo_moves._action_done(cancel_backorder=self.env.context.get('cancel_backorder'))
  File "/odoo/addons/kudu_stock/models/stock_move.py", line 28, in _action_done
    res = super()._action_done(cancel_backorder)
  File "/odoo/addons/osi_fifo_serialized_fix/models/stock_move.py", line 122, in _action_done
    self.get_svl_ids(move)
  File "/odoo/addons/osi_fifo_serialized_fix/models/stock_move.py", line 112, in get_svl_ids
    self.get_ji_ids(move, svl_ids)
  File "/odoo/addons/osi_fifo_serialized_fix/models/stock_move.py", line 33, in get_ji_ids
    if svl_id[3].product_id.tracking == "lot":
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 640, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 316, in _handle_exception
    raise exception.with_traceback(None) from new_cause
AttributeError: 'float' object has no attribute 'product_id'

**Review by smangukiya — CHANGES_REQUESTED** [review]
Need to resolve Error mentioned into comment.

**Comment by Hardik-OSI** [comment]
@smangukiya 
Here is the Improved commit :- https://github.com/ursais/osi-addons/pull/397/commits/8644811db72f1ae7475dc0a964e720257c3ebfc4
Can you please review it?
Thanks.

**Review by smangukiya — COMMENTED** [review]
Ready for testing

**Review by smangukiya — APPROVED** [review]

**Comment by patrickrwilson** [comment]
@Freni-OSI can you squash commits, then I think this PR is ready.

**Review by patrickrwilson — APPROVED** [review]
This has been tested in several projects and ready to merge into 14.0. LGTM

**Pull request merged**
