### PR TITLE
[14.0] [ADD] osi_crm_project: Added new module to create a task from CRM opportunity. (Ticket #17187)

### PR DESCRIPTION
**Pull request by Chandresh-OSI**
Ticket: https://pm.opensourceintegrators.com/web?debug=0#id=17187&action=324&model=helpdesk.ticket&view_type=form&menu_id=218

### CODE REVIEW

**Comment by patrickrwilson** [comment]
@Chandresh-OSI I've tested this and have a few adjustment that are needed, but I will notate them in the ticket.

**Comment by Chandresh-OSI** [comment]
@patrickrwilson I have fixed the code and it is now ready to test.

**Comment by patrickrwilson** [comment]
@Chandresh-OSI This works great, please fix pre-commit then I will approve.

**Comment by Chandresh-OSI** [comment]
@patrickrwilson pre-commit is not related to osi_crm_project module. Failing due to other modules.

**Review by patrickrwilson — APPROVED** [review]
Works great, LGTM

**Review by omahadik — APPROVED** [review]

**Comment by dreispt** [comment]
Is this very different from https://github.com/OCA/crm/tree/14.0/crm_project ?

**Comment by patrickrwilson** [comment]
@dreispt Yes, the OCA module converts an opportunity to a task, then deletes the opportunity which is not the functionality we need.

**Pull request merged**
