### PR TITLE
[14.0][IMP] fieldservice_mobile

### PR DESCRIPTION
**Pull request by murtuzasaleh**
Removed Dependancy from a module and configured it based on FSM Mobile Feature Mapping Functionality.

So now onwards mobile application does not depend on the previously added fieldservice_mobile module extra dependency.

Also From Mobile application team will visible records and menus based on the FSM Mobile Feature Mapping configuration.

Config

### CODE REVIEW

**Comment by MS-OSI** [comment]
@patrickrwilson Any reason to close this PR?

I don't know why there are multiple commits in my PR, When I created this PR it was only 4 commits.

@wolfhall has a demo with a client for a Mobile application on Monday and we need these module changes.

Cc @wolfhall

**Comment by patrickrwilson** [comment]
@MS-OSI there was a mistake made earlier, you may need to recreate the pr, sorry

**Comment by murtuzasaleh** [comment]
> @patrickrwilson Any reason to close this PR?
> 
> I don't know why there are multiple commits in my PR, When I created this PR it was only 4 commits.
> 
> @wolfhall has a demo with a client for a Mobile application on Monday and we need these module changes.
> 
> Cc @wolfhall

@ravosi

**Comment by murtuzasaleh** [comment]
Created New PR #490 

Cc @wolfhall @ravosi @max3903 @patrickrwilson @dreispt

**Pull request closed without merging**
