### PR TITLE
[14.0][FIX] osi_helpdesk_stock

### PR DESCRIPTION
**Pull request by Murtaza-OSI**
https://pm.opensourceintegrators.com/web?debug=1#id=13314&action=324&model=helpdesk.ticket&view_type=form&menu_id=218
image

### CODE REVIEW

**Comment by Murtaza-OSI** [comment]
https://pm.opensourceintegrators.com/web?debug=1#id=13312&action=324&model=helpdesk.ticket&view_type=form&menu_id=218
image

**Review by osi-scampbell — APPROVED** [review]

**Comment by Hardik-OSI** [comment]
Hello @max3903 
In This Branch Pre Commit Failed due to account_bank_statement_extend module.
for account_bank_statement_extend module pre-commit fixed in https://github.com/ursais/osi-addons/tree/14.0-fix-analytic_segments_defaults This Branch so once you merge this branch pre-commit Fixed.
Thanks.

**Comment by Murtaza-OSI** [comment]
rec = super(StockRequestOrder, self).action_confirm()

File "/opt/odoo/pavlov/pavlov-odoo/src/link-addons/osi_helpdesk_stock/models/stock_request_order.py", line 54, in action_confirm
self.procurement_group_id = group.id
File "/opt/odoo/pavlov/pavlov-odoo/odoo/odoo/fields.py", line 3815, in get
raise ValueError("Expected singleton: %s" % record)
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
File "/opt/odoo/pavlov/pavlov-odoo/odoo/odoo/http.py", line 640, in _handle_exception
return super(JsonRequest, self)._handle_exception(exception)
File "/opt/odoo/pavlov/pavlov-odoo/odoo/odoo/http.py", line 316, in _handle_exception
raise exception.with_traceback(None) from new_cause
ValueError: Expected singleton: procurement.group(753, 370)

**Comment by max3903** [comment]
@Urvisha-OSI Please fix this PR

**Comment by Urvisha-OSI** [comment]
> @Urvisha-OSI Please fix this PR

@max3903 the pre-commit issue is solved

**Pull request merged**
