### PR TITLE
[IMP] helpdesk_stock: Add SRO to SR list on a ticket

### PR DESCRIPTION
**Pull request by osi-scampbell**
Adds SRO to the SR Tree on Helpdesk Ticket

1/2 of Ticket #1197

### CODE REVIEW

**Comment by max3903** [comment]
This should go to `stock_request` module and only appears if the SRO setting is activated...

**Review by max3903 — CHANGES_REQUESTED** [review]
Wrong module

**Comment by osi-scampbell** [comment]
@max3903 But this depends on helpdesk which is an enterprise module? I did not think we can use enterprise modules in OCA? I can add SRO's to the base SR's tree, but the ticket only specifies this change on FSO's and Helpdesk Tickets.

**Comment by max3903** [comment]
My bad, I thought it was the list view of the stock requests.

**Review by max3903 — APPROVED** [review]

**Review by bodedra — APPROVED** [review]

**Comment by max3903** [comment]
@osi-scampbell I think you need to rebase to get Travis green.

**Review by patrickrwilson — APPROVED** [review]
Tested and looks good to me.

**Pull request merged**
