### PR TITLE
12.0 Add Avatax Connector App

### PR DESCRIPTION
**Pull request by dreispt**
From https://github.com/dreispt/avatax_connector/tree/12.0

### CODE REVIEW

**Review by b-kannan — COMMENTED** [review]
@dreispt : Addition of latitude and longitude as fields to res.partner -- crm modules adds partner_latitude and partner_longitude to partner model.

**Comment by dreispt** [comment]
@b-kannan Well spotted. I did that change, but I still need to run some tests on it.

**Comment by dreispt** [comment]
@b-kannan Implemented your suggestion and tested it.

Note: unfortunately, it is not working properly in CE, because of the hidden Accounting features (AR and Ap accounts are required, but field not visible, is the Partner form).
I'll deal with that later, IMO it is not blocking for the merge.

**Comment by dreispt** [comment]
@b-kannan is it OK to merge this?

**Comment by b-kannan** [comment]
There seems to be a Travis error (not sure why it is still an error when the 3rd iteration of the check was successful.
@dreispt : I am ok with the merge.

**Pull request merged**
