### PR TITLE
[16.0][MIG] Migrated osi_partner_credit_limit (V15 to V16)

### PR DESCRIPTION
**Pull request by Chanakya-OSI**

### CODE REVIEW

**Comment by agyamuta** [comment]
@Chanakya-OSI can we fix these 2 checks?
image
Thanks!

**Comment by Urvisha-OSI** [comment]
@agyamuta pre-commit fails because of osi_auth_oauth module that we don't have in this branch, the test fails because of a git authentications issue @dreispt will fix it

**Comment by dreispt** [comment]
@Urvisha-OSI Error is `osi_auth_oauth/__init__.py:1: [C7902(missing-readme), ] Missing ./README.rst file`
Please fix here it in a separate commit.
Thanks!

**Comment by Urvisha-OSI** [comment]
@dreispt the issue is from the osi_auth_oauth module that is not available in this branch should I do a new PR for it?

**Comment by dreispt** [comment]
Yes, please do.

**Comment by Urvisha-OSI** [comment]
refer https://github.com/ursais/osi-addons/pull/526 PR for resolve osi_auth_oauth module

**Comment by dreispt** [comment]
"All checks have passed"

**Pull request merged**
