### PR TITLE
[IMP] helpdesk_stock: Stock request workflow adjustment

### PR DESCRIPTION
**Pull request by osi-scampbell**
Same workflow we use in Fieldservice_stock. See this PR: https://github.com/OCA/field-service/pull/549

Edit: In order to maintain consistency with PR: https://github.com/OCA/stock-logistics-warehouse/pull/874 I have changed the header for the onchange methods in helpdesk_stock and fieldservice_helpdesk_stock

### CODE REVIEW

**Comment by patrickrwilson** [comment]
@osi-scampbell Testing, seems to work but I have a question. The delivery method doesn't carry over to the transfer, should it or is that in another module?

**Comment by osi-scampbell** [comment]
@patrickrwilson I believe that is an issue in Ticket #1853 Medium: Stock Requests - Multiple issues with missing analytic accounts context. I solved a lot of those but didn't get all of them in for the release. We should narrow that ticket down to see what is remaining. We can leave this PR open so I can move that fix here

**Comment by patrickrwilson** [comment]
@osi-scampbell it seems like it makes sense to have that fix here, then we can look at that ticket for whatever is left on it. Thanks.

**Review by max3903 — APPROVED** [review]

**Comment by max3903** [comment]
@osi-scampbell Can you fix Travis errors?

**Pull request merged**
